import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/student_models.dart';

/// Raw backend access used by [StudentService].
///
/// Kept separate so tests can drive the service without a live Supabase
/// instance. Implementations must let backend errors propagate unchanged.
abstract interface class StudentDataSource {
  /// Id of the signed-in user, or `null` when there is no session.
  String? get currentUserId;

  /// Calls the `create_minor_student` RPC and returns the new student id.
  Future<Object?> createMinorStudent(Map<String, dynamic> params);

  /// Returns active `student_guardians` rows joined with `students(*)`.
  Future<List<Map<String, dynamic>>> fetchGuardianStudentRows(
    String guardianUserId,
  );

  /// Returns active vans joined with their fleet and the schools it serves.
  Future<List<Map<String, dynamic>>> fetchActiveVanRows();

  /// Calls the `submit_fleet_join_request` RPC.
  Future<void> submitFleetJoinRequest(Map<String, dynamic> params);
}

/// [StudentDataSource] backed by the Supabase client.
class SupabaseStudentDataSource implements StudentDataSource {
  SupabaseStudentDataSource({SupabaseClient? client}) : _client = client;

  final SupabaseClient? _client;

  /// Resolves the client lazily so screens can be built before (or without,
  /// in tests) `Supabase.initialize`.
  SupabaseClient? get _resolvedClient {
    if (_client != null) return _client;
    try {
      return Supabase.instance.client;
    } catch (_) {
      return null;
    }
  }

  SupabaseClient get _requireClient {
    final client = _resolvedClient;
    if (client == null) throw StudentService.unauthenticated();
    return client;
  }

  @override
  String? get currentUserId => _resolvedClient?.auth.currentUser?.id;

  @override
  Future<Object?> createMinorStudent(Map<String, dynamic> params) {
    return _requireClient.rpc('create_minor_student', params: params);
  }

  @override
  Future<List<Map<String, dynamic>>> fetchGuardianStudentRows(
    String guardianUserId,
  ) {
    return _requireClient
        .from('student_guardians')
        .select('student_id, students(*)')
        .eq('guardian_user_id', guardianUserId)
        .eq('status', 'active');
  }

  @override
  Future<List<Map<String, dynamic>>> fetchActiveVanRows() {
    return _requireClient
        .from('vans')
        .select(
          'id, plate, model, public_name, capacity, fleet_id, '
          'fleets(name, fleet_service_schools(schools(id, name)))',
        )
        .eq('status', 'active');
  }

  @override
  Future<void> submitFleetJoinRequest(Map<String, dynamic> params) async {
    await _requireClient.rpc('submit_fleet_join_request', params: params);
  }
}

/// Guardian-facing student and marketplace operations.
///
/// Every method talks to the backend only: there are no local caches or
/// demo fallbacks. Backend failures propagate as [PostgrestException] so the
/// screens can map their `code` to pt-BR copy via `StudentErrorMapper`.
class StudentService {
  StudentService({SupabaseClient? client, StudentDataSource? dataSource})
    : _dataSource = dataSource ?? SupabaseStudentDataSource(client: client);

  final StudentDataSource _dataSource;

  /// Error raised when an operation requires a session and none exists.
  /// Mirrors the `unauthenticated` code from `private.raise_api_error`.
  static PostgrestException unauthenticated() => const PostgrestException(
    message: 'Authentication required',
    code: 'unauthenticated',
  );

  String _requireUserId() {
    final userId = _dataSource.currentUserId;
    if (userId == null) throw unauthenticated();
    return userId;
  }

  /// Creates a minor student managed by the signed-in guardian.
  ///
  /// Returns the id generated by the backend.
  /// Throws [PostgrestException] when signed out or when the RPC fails.
  Future<String> createMinorStudent({
    required String fullName,
    required String birthDate, // YYYY-MM-DD
    required String street,
    required String streetNumber,
    required String neighborhood,
    required String cityName,
    required String cityIbgeCode,
    required String stateCode,
    required String postalCode,
    required double latitude,
    required double longitude,
  }) async {
    _requireUserId();
    final result = await _dataSource.createMinorStudent({
      'p_full_name': fullName.trim(),
      'p_birth_date': birthDate.trim(),
      'p_postal_code': postalCode.trim(),
      'p_street': street.trim(),
      'p_street_number': streetNumber.trim(),
      'p_address_complement': null,
      'p_neighborhood': neighborhood.trim(),
      'p_city_name': cityName.trim(),
      'p_city_ibge_code': cityIbgeCode.trim(),
      'p_state_code': stateCode.trim(),
      'p_latitude': latitude,
      'p_longitude': longitude,
    });
    return result.toString();
  }

  /// Returns the students actively linked to the signed-in guardian.
  ///
  /// An empty list means the guardian has no students yet.
  /// Throws [PostgrestException] when signed out or when the query fails.
  Future<List<StudentProfile>> getMyStudents() async {
    final rows = await _dataSource.fetchGuardianStudentRows(_requireUserId());
    return [
      for (final row in rows)
        if (row['students'] case final Map<String, dynamic> student)
          StudentProfile.fromMap(student),
    ];
  }

  /// Returns active vans, one entry per school served by the van's fleet.
  ///
  /// Vans whose fleet serves no school are skipped because a join request
  /// requires a school id. An empty list means nothing is available.
  /// Throws [PostgrestException] when signed out or when the query fails.
  Future<List<AvailableVanFleet>> getAvailableVans() async {
    _requireUserId();
    final rows = await _dataSource.fetchActiveVanRows();
    final vans = <AvailableVanFleet>[];
    for (final row in rows) {
      final fleet = row['fleets'] as Map<String, dynamic>?;
      final servedSchools =
          fleet?['fleet_service_schools'] as List? ?? const [];
      for (final served in servedSchools) {
        final school = (served as Map<String, dynamic>)['schools'];
        if (school is! Map<String, dynamic>) continue;
        vans.add(
          AvailableVanFleet(
            fleetId: row['fleet_id'] as String,
            fleetName: fleet?['name'] as String? ?? '',
            vanPlate: row['plate'] as String,
            vanModel: row['model'] as String,
            vanPublicName: row['public_name'] as String,
            capacity: (row['capacity'] as num).toInt(),
            schoolId: school['id'] as String,
            schoolName: school['name'] as String,
          ),
        );
      }
    }
    return vans;
  }

  /// Submits a fleet join request for [studentId] at [schoolId].
  ///
  /// Throws [PostgrestException] when signed out or when the RPC rejects the
  /// request (e.g. `request_conflict`, `invalid_input`).
  Future<void> submitJoinRequest({
    required String fleetId,
    required String studentId,
    required String schoolId,
    required String shift,
  }) async {
    _requireUserId();
    await _dataSource.submitFleetJoinRequest({
      'p_fleet_id': fleetId,
      'p_student_id': studentId,
      'p_school_id': schoolId,
      'p_shift': shift,
      'p_directions': ['going', 'return'],
      'p_weekdays': [1, 2, 3, 4, 5],
    });
  }
}
